from google import genai
from dotenv import load_dotenv
import os
from config import gemini_config
load_dotenv()




gemini_api_key = os.getenv("GEMINI_API_KEY")
client = genai.Client(api_key=gemini_api_key)


def stream_gemini(prompt): 
    for chunk in client.models.generate_content_stream(
        model=gemini_config["model_name"],
        config=gemini_config["config"],
        contents=prompt
    ) :
        yield chunk.text 


def build_gemini_prompt(original_query: str, slm_response: str) -> str:
    if slm_response:
        return f"""You are refining an answer generated by a smaller model.

Original question: {original_query}

Draft answer from smaller model:
{slm_response}

Your task: Improve this answer. Fix any errors, add depth, improve clarity. 
Be direct — do not say things like "the previous answer said..." just give the improved answer."""
    else:
    
        return original_query
